language: generic

env:
    global:
        - APM_TEST_PACKAGES=""
        - ATOM_LINT_WITH_BUNDLED_NODE="true"

    matrix:
        - ATOM_CHANNEL=stable
        - ATOM_CHANNEL=beta

os:
    - linux
    - osx

install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libgconf2-4; fi

script:
    - ./scripts/travis.sh

notifications:
    email:
        on_success: never
        on_failure: change

branches:
    only:
        - master

git:
    depth: 10

sudo: false

dist: bionic

addons:
    apt:
        packages:
            - build-essential
            - fakeroot
            - git
            - libsecret-1-dev
