environment:
    APM_TEST_PACKAGES:
    ATOM_LINT_WITH_BUNDLED_NODE: "true"
    matrix:
        - ATOM_CHANNEL: stable
        - ATOM_CHANNEL: beta

install:
    - ps: Install-Product node $env:nodejs_version $env:platform

build_script:
    - ps: scripts\appveyor.ps1

branches:
    only:
        - master

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
